version: '3.4'

services:
    php:
        build: ./docker/php
        volumes:
            - ./:/var/www:rw
        depends_on:
            - db
            - redis
    web:
        build: ./docker/web
        ports:
            - "80:80"
        volumes:
            - ./:/var/www:ro
        depends_on:
            - php
    proxy:
        # Don't use this proxy in prod
        build: ./docker/proxy
        depends_on:
          - web
        ports:
          - "443:443"
    db :
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - /srv/mariadb:/var/lib/mysql
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - db
    redis:
        image: redis:latest
        command: ["redis-server", "--appendonly", "yes"]
        ports:
            - "6379:6379"
        volumes:
            - /srv/redis:/data