version: '3.4'
services:
    php:
        build: ./docker
        volumes:
            - ./:/var/www/
            - ./docker/php.ini:/usr/local/etc/php/php.ini
        links:
            - db
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    db :
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ~/mariadb:/var/lib/mysql
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db